### ISSUE TITLE
Files?

### ISSUE THREAD

**Issue by pmuntner** [jhs-hwg/cardioStatsUSA#30]
Is there a way to share files through Github. I assume there is.....

**Comment by bcjaeger** [comment]
Yep! A pull request would do the trick, although those are usually best for sharing code. I am happy to grab the file from Box if that is more convenient.

**Comment by pmuntner** [comment]
What is a pull request - maybe you can show me this on Wednesday.

**Comment by bcjaeger** [comment]
Definitely! Should take about 10-15m depending on time spent setting up Git and GitHub.

**Comment by bcjaeger** [comment]
Fixed this with Box.
