### ISSUE TITLE
Calibrating nhanes weights in the app

### ISSUE THREAD

**Issue by bcjaeger** [jhs-hwg/cardioStatsUSA#31]
It would be awesome to have a reliable and fast mechanism for calibrating NHANES weights in the Shiny app, as this would make it much easier for us to analyze cohorts based on subpopulations with _observed_ data for specific variables and still get an estimated count in our subpopulations that matches the full estimated count according to the NHANES survey weights. Potential problems with doing this: 

1. Is it slow??
2. Can we use the same age/sex/race groups as in our usual age/sex/race variables? I think the concern here is that some of the groups may have small sample sizes. We should discuss this.

I took a stab at writing a fast function and tested it below. According to the benchmark in the code below, this runs in about 30ms on average (max is about 250 ms) when using the full NHANES data and calibrating across each cycle within age/sex/race groups. Will it run slower on the server versus my CPU with way too many cores? Sure, but probably still less than 100ms. 

I think @pmuntner and I should discuss item 2 and then make sure this function gives the same weights as his SAS code when I use the exact same age/sex/race groups as his SAS code. Just need to get clarification on those groups. Would be great to discuss this in Wednesday's meeting.

``` r
library(nhanesShinyBP)
library(data.table)
library(magrittr)
data(nhanes_bp, package = 'nhanesShinyBP')

# nhanes full is the full nhanes data
# nhanes sub is a subset of nhanes full that we will calibrate weights in
# calib_by defines the groups we'll calibrate weights in

nhanes_calibrate <- function(nhanes_full,
                             nhanes_sub,
                             calib_by = c('svy_year',
                                          'demo_age_cat',
                                          'demo_gender',
                                          'demo_race')){
 
 # find total sum of weights across all combinations of the by groups
 # .full is for the full population, .sub is among the subpop
 .full <- nhanes_full[,.(total = sum(svy_weight_mec)), keyby = calib_by]
 .sub <- nhanes_sub[, .(partial = sum(svy_weight_mec)),  keyby = calib_by]
 
 # merge and compute the ratio that will be used to calibrate weights
 .calib <- merge(.full, .sub)[, ratio := total / partial] %>%
  # not needed, but drop the total and partial column
  .[, `:=`(total = NULL, partial = NULL)]
 
 # return nhanes_sub with calibrated weights
 nhanes_sub[.calib, on = calib_by] %>%
  .[, svy_weight_cal := svy_weight_mec * ratio]
 
}

# benchmark the nhanes_calibrate function
# takes about ~30-35 milliseconds on average
microbenchmark::microbenchmark(
 bcj_calib = nhanes_calibrate(nhanes_full = nhanes_bp, 
                              nhanes_sub = nhanes_bp[svy_subpop == 1])
)
#> Unit: milliseconds
#>       expr     min     lq     mean  median      uq      max neval
#>  bcj_calib 24.7913 26.616 38.98808 29.6759 30.5366 259.5373   100

# check to make sure the sum of weights in the new 
# data match the sum of weights in the original data

nhanes_calib <- nhanes_calibrate(nhanes_bp,
                 nhanes_sub = nhanes_bp[svy_subpop == 1])

sum(nhanes_calib$svy_weight_cal)
#> [1] 2244544303
sum(nhanes_bp$svy_weight_mec)
#> [1] 2244544303
```

<sup>Created on 2022-07-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ligongus** [comment]
The calib_by = c(...) inside the function should not be fixed. Sometimes we may not calibrate by svy_year or some demo variable(s).  Also this function can only apply to analyses for individual cycles but not to those for combined cycles. To make the weight flexible to be used, can we put the weight variable (it can be a weight for individual cycles or one for combined cycles) inside the function, i.e. , nhanes_calibrate <- function(nhanes_full,
                             nhanes_sub,
                             weight, 
                             calib_by = c()){............}

**Comment by ligongus** [comment]
Should we compare the resulted design from this calibration with the design resulted from the svystandardize survey function?

**Comment by bcjaeger** [comment]
> Should we compare the resulted design from this calibration with the design resulted from the svystandardize survey function?

I am not sure about this. Does it make sense to use `svystandardize` if the objective is to estimate counts?

**Comment by bcjaeger** [comment]
> The calib_by = c(...) inside the function should not be fixed. Sometimes we may not calibrate by svy_year or some demo variable(s).

I don't think it is fixed, e.g. we could call

```r
nhanes_calib <- nhanes_calibrate(nhanes_bp,
                                                      nhanes_sub = nhanes_bp[svy_subpop == 1], 
                                                      calib_by = c('svy_year')
```

and it would just calibrate over the survey years.

**Comment by bcjaeger** [comment]
> Also this function can only apply to analyses for individual cycles but not to those for combined cycles

I think we can do combined cycles if we omit 'svy_year' from the `calib_by` input.

**Comment by bcjaeger** [comment]
> can we put the weight variable (it can be a weight for individual cycles or one for combined cycles) inside the function

Maybe - we could make the name of the weight variable one of the inputs. Do we have a scenario where the weight variable wouldn't be some version of the 2-year mec weights?

**Comment by ligongus** [comment]
Also this function can only apply to analyses for individual cycles but not to those for combined cycles

I think we can do combined cycles if we omit 'svy_year' from the calib_by input.

Sometimes we combine for every two cycles but not all the cycles.

**Comment by ligongus** [comment]
can we put the weight variable (it can be a weight for individual cycles or one for combined cycles) inside the function

Maybe - we could make the name of the weight variable one of the inputs. Do we have a scenario where the weight variable wouldn't be some version of the 2-year mec weights?

We may use different types of weights such as examination weights, fasting subsample weights. Also the weight variable name is different in the 2017-March 2020 cycle. There is no problem with current data, because we used a newly created weight variable. If we want to use the original weight variable, there will be a problem. In the future, we may still need to create a new weight variable from the original weight variable.

**Comment by bcjaeger** [comment]
> Sometimes we combine for every two cycles but not all the cycles.

This is a great point. At the moment, users can only do analyses stratified by cycle or in one pooled set of survey years. We'll have to update `nhanes_calibrate` if the app ever gets more flexible wrt survey years.

**Comment by bcjaeger** [comment]
Implemented in the app now! But easy to take out if we need to re-consider.
