### ISSUE TITLE
instructions delivery

### ISSUE THREAD

**Issue by bcjaeger** [jhs-hwg/cardioStatsUSA#46]
Feedback from expert user:

> I wonder if it’s possible to place the “next” and “back” bottoms more to the center of the instruction bubbles. Because it’s quite easy to accidentally click outside of the box, then it’ll reset and users need to go from the beginning again. OR, can each section have its own question mark/instruction, in addition to the overall instruction panel? So if a user just wants to read about the last part, they don’t need to go back to the beginning and click through all the “next”s.

I very much like both of these ideas, and I think the second one would be easy to do with `rintrojs` hints.

@ligongus would you like to try this one? It would not require too much digging into my code and would maybe be a good skill to learn for future shiny applications.

**Comment by bcjaeger** [comment]
Additional related feedback:

> I think it is necessary to further explain how to adjust age distribution.

I agree with this. The `introBox` function isn't ideal for this because the age distribution ui is conditionally hidden. 

A hint would work well here I think.

**Comment by ligongus** [comment]
I think it's a good idea! I will work on it.

**Comment by bcjaeger** [comment]
Great! Do you remember how to open a new branch and then start a PR? I can help with this if you'd like.

**Comment by ligongus** [comment]
That would be great. I will have time between 10:45 AM and 1:00 PM today.

**Comment by ligongus** [comment]
I tried and could not find the website for hint.

**Comment by bcjaeger** [comment]
No problem - https://carlganz.github.io/rintrojs/

**Comment by ligongus** [comment]
Got it. Thanks.

**Comment by bcjaeger** [comment]
Great! Can you do the items below?

1. Commit your changes
2. Push the commit (it should automatically go to the branch you opened)
3. Verify that the commit shows up in your pull request: https://github.com/jhs-hwg/cardioStatsUSA/pull/50

I'll review the changes and may have some comments/edits. Maybe we can meet to discuss after?

**Comment by ligongus** [comment]
I just did it and saw the commit in the pull request.
We can modify the words related to the hint if it's necessary.

**Comment by bcjaeger** [comment]
Thanks! I'll review soon.
